target-version = "py311"

line-length = 79

[lint]
select = ["ALL"]
ignore = [
    "D203", # No blank line before class docstring.
    "D213", # Fix bad default.
    "ERA001", # Commented out code.
    "S101",  # Use of `assert` statement.
    "RET504",  # Assignment right before return.
    "COM812", # Missing comma at the end of a function call. Bad in show() call.
    "D100", # Missing docstring in public module.
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[format]
# Like Black, use double quotes for strings.
quote-style = "double"
