name: Lint, Type Check, and Run Python Code

on: [push]

jobs:
  lint-with-ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff linter
        run: ruff check .

  check-with-pyright:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install pyright
        run: pip install pyright

      - name: Run pyright
        run: pyright .


  run-python-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install -r requirements.txt
        
      - name: Run Python scripts in CAD folder
        run: |
          find cad -name "*.py" | while read file; do
            echo "Running $file"
            python "$file"
          done
